---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ amq_broker_operator_name }}"
    install_operator_namespace: "{{ amq_broker_operator_namespace }}"
    install_operator_channel: "{{ amq_broker_operator_channel }}"
    install_operator_csv_nameprefix: "{{ amq_broker_operator_csv_prefix }}"
    install_operator_catalog: "{{ amq_broker_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ amq_broker_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ amq_broker_operator_starting_csv }}"
    install_operator_catalogsource_setup: "{{ amq_broker_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ amq_broker_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: "{{ amq_broker_operator_catalogsource_namespace }}"
    install_operator_catalogsource_image: "{{ amq_broker_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ amq_broker_operator_catalog_snapshot_image_tag | default('') }}"

