---

- name: Get ingress domain
  kubernetes.core.k8s_info:
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    api_version: operator.openshift.io/v1
  register: r_openshift_ingress_controller

- name: Set openshift domain
  ansible.builtin.set_fact:
    r_openshift_subdomain: "{{ r_openshift_ingress_controller.resources[0].status.domain }}"
    
- name: Remove application
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'application.yaml.j2') | from_yaml }}"

- name: Remove application namespace
  kubernetes.core.k8s:
    state: absent
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
