---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ operator_rhbk_name }}"
    install_operator_namespace: "{{ operator_rhbk_namespace }}"
    install_operator_channel: "{{ operator_rhbk_channel }}"
    install_operator_csv_nameprefix: "{{ operator_rhbk_csv_prefix }}"
    install_operator_catalog: "{{ operator_rhbk_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ operator_rhbk_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ operator_rhbk_starting_csv }}"
    install_operator_manage_namespaces:
      - "{{ operator_rhbk_namespace }}"
    install_operator_catalogsource_setup: "{{ operator_rhbk_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ operator_rhbk_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: "{{ operator_rhbk_catalogsource_namespace }}"
    install_operator_catalogsource_image: "{{ operator_rhbk_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ operator_rhbk_catalog_snapshot_image_tag | default('') }}"
