---

# OCP4 Authentication:
ocp4_workload_authentication_htpasswd_user_password: openshift
ocp4_workload_authentication_htpasswd_user_base: user
ocp4_workload_authentication_htpasswd_user_count: 1

# Shared Users
ocp4_workload_user_count: "{{ ocp4_workload_authentication_htpasswd_user_count }}"
ocp4_workload_user_prefix: "{{ ocp4_workload_authentication_htpasswd_user_base }}"


# ------------------------------------------------
# Workshop
# ------------------------------------------------

# Namespaces
namespace_prefix: globex

# ApplicationSet
applicationset_name: globex-gitops
applicationset_namespace: openshift-gitops

argo_application_name: globex-gitops
argo_application_namespace_prefix: "{{ namespace_prefix }}-gitops"
argo_application_namespace: >-
  {{ argo_application_namespace_prefix }}-base

globex_application_name: globex

application_repo: https://github.com/rh-cloud-architecture-workshop/helm.git
application_repo_tag: main
application_repo_path_gitops: globex-gitops/common
application_repo_path_globex: globex

kafka_security_protocol: SASL_PLAINTEXT
kafka_sasl_mechanism: SCRAM-SHA-512
kafka_client_id: globex
kafka_client_secret: globex

globex_user_password: openshift


# ------------------------------------------------
# Red Hat build of Keycloak
# ------------------------------------------------

rhbk_application_namespace: openshift-gitops
rhbk_application_name: rhbk
rhbk_namespace: "{{ operator_rhbk_namespace }}"
rhbk_gitops_repo: https://github.com/rh-cloud-architecture-workshop/helm.git
rhbk_gitops_repo_tag: main
rhbk_gitops_repo_path: globex-keycloak

rhbk_cr_name: rhbk
rhbk_external_access: false
rhbk_host: sso
rhbk_max_time_to_wait: 600000

rhbk_realm: globex
rhbk_web_gateway_client: globex-web-gateway
