---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ operator_camelk_name }}"
    install_operator_namespace: "{{ operator_camelk_namespace }}"
    install_operator_channel: "{{ operator_camelk_channel }}"
    install_operator_csv_nameprefix: "{{ operator_camelk_csv_prefix }}"
    install_operator_catalog: "{{ operator_camelk_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ operator_camelk_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ operator_camelk_starting_csv }}"
    install_operator_catalogsource_setup: "{{ operator_camelk_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ operator_camelk_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: "{{ operator_camelk_catalogsource_namespace }}"
    install_operator_catalogsource_image: "{{ operator_camelk_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ operator_camelk_catalog_snapshot_image_tag | default('') }}"
